name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  # Check if there any dirty change for go mod tidy
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: lint
          uses: golangci/golangci-lint-action@v2.5.2
          with:
            version: latest
            # skip cache because of flaky behaviors
            skip-build-cache: true
            skip-pkg-cache: true
      - uses: pre-commit/action@v2.0.3
